from slack_sdk import WebClient
from slack_sdk.errors import SlackApiError
from app.core.config import settings


def get_slack_client() -> WebClient:
    """Create and return Slack client."""
    return WebClient(token=settings.slack_bot_token)


async def send_slack_message(
    message: str,
    channel: str = None
) -> bool:
    """
    Send message to Slack channel.
    
    Args:
        message: message to send
        channel: channel name (default from .env)
    
    Returns:
        True if sent, False if failed
    """
    try:
        client = get_slack_client()
        channel = channel or settings.slack_default_channel

        response = client.chat_postMessage(
            channel=channel,
            text=message
        )
        return response["ok"]

    except SlackApiError as e:
        print(f"Slack error: {e.response['error']}")
        return False
    except Exception as e:
        print(f"Slack error: {e}")
        return False


async def send_incident_notification(
    jira_ticket_id: str,
    root_cause: str,
    recommendation: str,
    confidence_score: float
) -> bool:
    """
    Send formatted incident notification to Slack.
    """
    message = f"""
🚨 *New Incident Detected!*
─────────────────────────
*Jira Ticket:* {jira_ticket_id}
*Root Cause:* {root_cause[:200]}
*Recommendation:* {recommendation[:200]}
*Confidence Score:* {confidence_score}
─────────────────────────
_Auto generated by Workflow Platform_
    """

    return await send_slack_message(message)